name: Pull Request Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout branch from repository
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Setup node environment
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Specify the Node.js version required for your project

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Build the Angular project
      - name: Build project
        run: npm run build

      # Run unit tests
      - name: Run unit tests
        run: npm test